version: '3.1'

services:
  web:
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    env_file:
      - .env
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always
  db:
    image: postgres:16
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  odoo-web-data:
  odoo-db-data:

